/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes -------------------------------------------------------------------*/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include <stdbool.h>
#include "defines.h"
#include "delay.h"
#include "button.h"
#include "FIRCoeff.h"
#include "arm_math.h"
/*Typedef --------------------------------------------------------------------*/


/*Defines ------------------------------------------------------------------- */
#define LED		D , 12
#define SW		A , 0
#define IN1		A , 1
/*Global variables ---------------------------------------------------------- */
Button_t button1;
bool adcComplet = false;
float32_t in;
float32_t out;
#define BLOCKSIZE 		1
float32_t FirState[K + BLOCKSIZE - 1];
arm_fir_instance_f32 filtro;
/*function prototype ---------------------------------------------------------*/
void ADC1_Init(void);
/*main function --------------------------------------------------------------*/

int main(void)
{

	printf("EJEMPLO GPIO1\r\n");
	printf("%s, %s\r\n", __DATE__, __TIME__);


	//init filter
	arm_fir_init_f32(&filtro, K, h, FirState, BLOCKSIZE);
	//PD12 (LED1)
	RCC->AHB1ENR |= GPIOX_CLOCK(LED) | GPIOX_CLOCK(SW);
	GPIOX_MODER(MODE_OUT, LED);
	GPIOX_OTYPER(MODE_OT_PP, LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH, LED);
	GPIOX_PUPDR(MODE_PU_NONE, LED);

	//PA0
	GPIOX_MODER(MODE_DIGITAL_INPUT, SW);
	GPIOX_PUPDR(MODE_PU_NONE, SW);
	//systick
	SysTickInit();

	//inicializar
	ButtonInit(&button1, GPIOA, 0, NULL);
	//adc init
	ADC1_Init();
	//configurar los canales
	RCC->AHB1ENR |= GPIOX_CLOCK(IN1);
	GPIOX_MODER(MODE_ANALOG_INPUT, IN1);
	GPIOX_PUPDR(MODE_PU_NONE, IN1);
	//Sequencer
	ADC1->SQR1 &=~ (ADC_SQR1_L);		//una sola conversion
	ADC1->SQR3 = 1;						//IN1
	//Habilita el ADC
	ADC1->CR2 |= ADC_CR2_ADON;
	/*timer 2 init -------------------------------------*/
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	/**
	 * Update envent  = Ftim / (PSC + 1) (ARR + 1)
	 * PSC = 15
	 * ARR = 16E+6 / (16 * 500) - 1
	 * ARR = 2000 - 1 = 1999
	 */
	TIM2->PSC = 15;
	TIM2->ARR = 1999;
	//Habilitar la salida TRGO
	TIM2->CR2 &=~ TIM_CR2_MMS;
	TIM2->CR2 |= TIM_CR2_MMS_1;		//habilita el TGRO para el disparo del adc
    //Habilitar el conteo
	TIM2->CR1 |= TIM_CR1_CEN;
	/* Loop forever */
	for(;;){
		if(ButtonRead(&button1, PIN_TO_LOW)){
			//todo
		}
		if(adcComplet == true){
			//procesado
			arm_fir_f32(&filtro, &in, &out, 1);
			printf("in: %.3f out: %.3f\r\n", in, out);
		}

	}
}

/*Function definition ---------------------------------------------------------*/

void ADC1_Init(void){
	//HABILITAR EL RELOJ
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	//Configurar los rigistros comunes entre ADC1, ADC2, ADC3
	ADC123_COMMON->CCR &=~ ADC_CCR_ADCPRE;				//PCLK2 / 2
	//Configurar los registros del ADC1
	ADC1->CR1 = 0;
	ADC1->CR1 |= ADC_CR1_OVRIE;				//Generar IT cuando se sobrescribe el dato convertido
	ADC1->CR1 |= ADC_CR1_EOCIE;				//generar IT cuando se termine de realizar la conversion

	ADC1->CR2 |= ADC_CR2_EXTEN_0;			//disparo con flanco acendente
	ADC1->CR2 |= ADC_CR2_EXTSEL_1 | ADC_CR2_EXTSEL_2; //disparo por timer2 out event
	//AWDG
	NVIC_EnableIRQ(ADC_IRQn);

	return;
}
/**
 * @adc callback
 */
void ADC1_CpltConvCallback(uint16_t data){
	//todo
	//printf("data->%u\r\n", data);
	adcComplet = true;
	in = data;
}

int __io_putchar(int ch){
	ITM_SendChar(ch);
	return ch;
}
